
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Apr 17 2024 17:00:50 +07 (Apr 17 2024 10:00:50 UTC)

// Verification Directory fv/ALU 

module ALU(a, b, control, result, zero);
  input [7:0] a, b;
  input [3:0] control;
  output [7:0] result;
  output zero;
  wire [7:0] a, b;
  wire [3:0] control;
  wire [7:0] result;
  wire zero;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_53;
  NOR4X1 g1720__2398(.A (result[4]), .B (result[5]), .C (result[6]), .D
       (n_53), .Y (zero));
  OR4X1 g1721__5107(.A (result[1]), .B (result[2]), .C (n_40), .D
       (result[7]), .Y (n_53));
  OAI221X1 g1722__6260(.A0 (control[1]), .A1 (n_4), .B0 (n_47), .B1
       (n_49), .C0 (n_22), .Y (result[7]));
  OAI211X1 g1723__4319(.A0 (control[1]), .A1 (n_6), .B0 (n_18), .C0
       (n_48), .Y (result[6]));
  XNOR2X1 g1724__8428(.A (n_45), .B (n_25), .Y (n_49));
  NAND2BXL g1725__5526(.AN (n_47), .B (n_46), .Y (n_48));
  ADDFX1 g1726__6783(.A (a[6]), .B (n_15), .CI (n_42), .CO (n_45), .S
       (n_46));
  OAI211X1 g1727__3680(.A0 (control[1]), .A1 (n_1), .B0 (n_17), .C0
       (n_44), .Y (result[5]));
  NAND2BXL g1728__1617(.AN (n_47), .B (n_43), .Y (n_44));
  ADDFX1 g1729__2802(.A (a[5]), .B (n_8), .CI (n_36), .CO (n_42), .S
       (n_43));
  OAI211X1 g1730__1705(.A0 (control[1]), .A1 (n_7), .B0 (n_11), .C0
       (n_41), .Y (result[4]));
  NAND2BXL g1731__5122(.AN (n_47), .B (n_37), .Y (n_41));
  OR2X1 g1732__8246(.A (result[0]), .B (result[3]), .Y (n_40));
  ADDFX1 g1733__7098(.A (a[4]), .B (n_12), .CI (n_33), .CO (n_36), .S
       (n_37));
  OAI211X1 g1734__6131(.A0 (control[1]), .A1 (n_5), .B0 (n_20), .C0
       (n_35), .Y (result[3]));
  NAND2BXL g1735__1881(.AN (n_47), .B (n_34), .Y (n_35));
  ADDFX1 g1736__5115(.A (a[3]), .B (n_13), .CI (n_30), .CO (n_33), .S
       (n_34));
  OAI211X1 g1737__7482(.A0 (control[1]), .A1 (n_3), .B0 (n_14), .C0
       (n_32), .Y (result[2]));
  NAND2BXL g1738__4733(.AN (n_47), .B (n_31), .Y (n_32));
  ADDFX1 g1739__6161(.A (a[2]), .B (n_9), .CI (n_27), .CO (n_30), .S
       (n_31));
  OAI211X1 g1740__9315(.A0 (control[1]), .A1 (n_2), .B0 (n_19), .C0
       (n_29), .Y (result[1]));
  NAND2BXL g1741__9945(.AN (n_47), .B (n_28), .Y (n_29));
  OAI2BB1X1 g1743__2883(.A0N (a[0]), .A1N (n_24), .B0 (n_26), .Y
       (result[0]));
  ADDFX1 g1742__2346(.A (a[1]), .B (n_21), .CI (n_16), .CO (n_27), .S
       (n_28));
  OAI21XL g1744__1666(.A0 (control[0]), .A1 (n_23), .B0 (b[0]), .Y
       (n_26));
  XNOR2X1 g1745__7410(.A (a[7]), .B (n_10), .Y (n_25));
  OAI21XL g1746__6417(.A0 (b[0]), .A1 (n_47), .B0 (n_0), .Y (n_24));
  MXI2XL g1747__5477(.A (n_47), .B (control[1]), .S0 (a[0]), .Y (n_23));
  OAI21XL g1752__2398(.A0 (b[7]), .A1 (a[7]), .B0 (control[0]), .Y
       (n_22));
  MX2X1 g1762__5107(.A (control[2]), .B (a[0]), .S0 (b[0]), .Y (n_21));
  OAI21XL g1748__6260(.A0 (b[3]), .A1 (a[3]), .B0 (control[0]), .Y
       (n_20));
  OAI21XL g1749__4319(.A0 (b[1]), .A1 (a[1]), .B0 (control[0]), .Y
       (n_19));
  OAI21XL g1750__8428(.A0 (b[6]), .A1 (a[6]), .B0 (control[0]), .Y
       (n_18));
  OAI21XL g1751__5526(.A0 (b[5]), .A1 (a[5]), .B0 (control[0]), .Y
       (n_17));
  CLKXOR2X1 g1761__6783(.A (control[2]), .B (b[1]), .Y (n_16));
  CLKXOR2X1 g1758__3680(.A (control[2]), .B (b[6]), .Y (n_15));
  OAI21XL g1754__1617(.A0 (b[2]), .A1 (a[2]), .B0 (control[0]), .Y
       (n_14));
  CLKXOR2X1 g1755__2802(.A (control[2]), .B (b[3]), .Y (n_13));
  CLKXOR2X1 g1756__1705(.A (control[2]), .B (b[4]), .Y (n_12));
  OAI21XL g1753__5122(.A0 (b[4]), .A1 (a[4]), .B0 (control[0]), .Y
       (n_11));
  XNOR2X1 g1757__8246(.A (control[2]), .B (b[7]), .Y (n_10));
  CLKXOR2X1 g1759__7098(.A (control[2]), .B (b[2]), .Y (n_9));
  CLKXOR2X1 g1760__6131(.A (control[2]), .B (b[5]), .Y (n_8));
  NAND2XL g1764__1881(.A (a[4]), .B (b[4]), .Y (n_7));
  NAND2XL g1763__5115(.A (a[6]), .B (b[6]), .Y (n_6));
  NAND2XL g1765__7482(.A (a[3]), .B (b[3]), .Y (n_5));
  NOR2X1 g1766__4733(.A (control[1]), .B (control[2]), .Y (n_47));
  NAND2XL g1770__6161(.A (a[7]), .B (b[7]), .Y (n_4));
  NAND2XL g1769__9315(.A (a[2]), .B (b[2]), .Y (n_3));
  NAND2XL g1767__9945(.A (a[1]), .B (b[1]), .Y (n_2));
  NAND2XL g1768__2883(.A (a[5]), .B (b[5]), .Y (n_1));
  INVXL g1771(.A (control[0]), .Y (n_0));
endmodule

